FROM microsoft/dotnet:1.0.0-core

# Set the Working Directory
WORKDIR /app

# Configure the listening port to 5000
ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000

# Copy the Debugger
COPY /clrdbg /clrdbg
RUN chmod 700 -R /clrdbg

# Copy the app
COPY /app /app

# If we are launching through a remote debugger wait for it, otherwise start the app
ENTRYPOINT ["/bin/bash", "-c", "if [ \"$REMOTE_DEBUGGING\" -eq 0 ]; then dotnet ruckit-core.web.dll; else sleep infinity; fi"]
